/*import java.awt.*;
import javax.swing.*;

public class MyGraphicsApp extends JFrame {

    public MyGraphicsApp() {
        setTitle("My First Graphic Design in Java");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        g.setFont(new Font("Times New Roman", Font.BOLD + Font.ITALIC, 24));
        g.drawString("Mulut saya hitam tapi saya biru", 45, 50);
        
        g.setColor(Color.RED);
        g.drawLine(5, 70, 380, 70);
        
        g.setColor(Color.BLUE);
        g.fillArc(100, 120, 180, 180, 360, 360);

        g.setColor(Color.RED);
        g.fillArc(150, 165, 30, 30, 360, 360);

        g.setColor(Color.RED);
        g.fillArc(200, 165, 30, 30, 360, 360);

        g.setColor(Color.BLACK);
        g.fillRect(145, 235, 90, 30);
    }

    public static void main(String[] args) {
        new MyGraphicsApp();
    }
} 


/* 
public class TestExceptionHandling{
public static void main(String str[]){
int y = 1;
int x = 1;
// try block to "SEE" if an exception occurs
try{
int z = x/y;
System.out.println("after division" + " " + z);
/* catch clause below handles the ArithmeticException generated by
the division by zero.} 
catch (ArithmeticException ae)
{System.out.println(" attempt to divide by 0");
}
System.out.println(" after catch ");

}} */
